# Generated by Django 4.2.5 on 2023-09-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0002_idea_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='movie_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
