# Generated by Django 4.2.5 on 2023-09-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0003_idea_comment_idea_movie_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='movie_name',
            new_name='software_idea',
        ),
    ]
