# Generated by Django 4.2.5 on 2023-09-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0004_rename_movie_name_idea_software_idea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='comment',
        ),
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(upload_to='ideas/'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='software_idea',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
